CREATE DATABASE projeto_react;
USE projeto_react;

CREATE TABLE users (
	uuid VARCHAR(36) PRIMARY KEY UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
    photo VARCHAR(255)
);

CREATE TABLE messages (
	id INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    userId VARCHAR(36) NOT NULL,
    prompt VARCHAR(2500) NOT NULL,
    message VARCHAR(2500) NOT NULL,
    FOREIGN KEY (userId) REFERENCES users(uuid)
);

CREATE TABLE emails (
	id INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    userId VARCHAR(36) NOT NULL,
    message VARCHAR(2500) NOT NULL,
    timestamp DATETIME NOT NULL
);
